DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
     id SERIAL PRIMARY KEY,
     first_name VARCHAR NOT NULL,
     last_name VARCHAR NOT NULL,
     email VARCHAR NOT NULL UNIQUE,
     password VARCHAR NOT NULL,
     img_url VARCHAR,
     bio VARCHAR,
     created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS secretcode CASCADE;

CREATE TABLE secretcode (
     id SERIAL PRIMARY KEY,
     email VARCHAR NOT NULL,
     secret_code VARCHAR NOT NULL,
     created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);